### ISSUE TITLE
UNREACHEABLE, stock in the first chapter

### ISSUE THREAD

**Issue by wvelez6** [PacktPublishing/Learn-Ansible-Second-Edition#1]
So I have tried to run the very first ansible command from chapter one, ansible -i hosts-simple 192.###.##.##.nip.io -m ansible.builtin.setup, and I keep getting unreacheable. As you can see below, I tried a ping with the nip.io and it says unknown host but when I ping just the ip, I get ping back. I have tried to use the ansible command by removing the nip.io from both hosts files and still unreacheable. I have run to the same on Ubuntu 24.04 and macOS running the latest Ansible. Any help please?

❯ multipass info ansiblevm
Name:           ansiblevm
State:          Running
Snapshots:      0
IPv4:           192.168.64.16
Release:        Ubuntu 24.04 LTS
Image hash:     5fe06e10a3b5 (Ubuntu 24.04 LTS)
CPU(s):         1
Load:           0.00 0.00 0.00
Disk usage:     1.8GiB out of 4.8GiB
Memory usage:   197.8MiB out of 953.1MiB
Mounts:         --

/Volumes/techops/Learn-Ansible-Second-Edition/Chapter01 main                                                                                                                           ansible9 10:11:00 PM
❯ ansible -i hosts-simple 192.168.64.16.nip.io -m ansible.builtin.setup
192.168.64.16.nip.io | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname 192.168.64.16.nip.io: nodename nor servname provided, or not known",
    "unreachable": true
}

/Volumes/techops/Learn-Ansible-Second-Edition/Chapter01 main                                                                                                                           ansible9 10:11:14 PM
❯ ping 192.168.64.16.nip.io
ping: cannot resolve 192.168.64.16.nip.io: Unknown host

/Volumes/techops/Learn-Ansible-Second-Edition/Chapter01 main                                                                                                                           ansible9 10:11:31 PM
❯ ping 192.168.64.16
PING 192.168.64.16 (192.168.64.16): 56 data bytes
64 bytes from 192.168.64.16: icmp_seq=0 ttl=64 time=0.564 ms
64 bytes from 192.168.64.16: icmp_seq=1 ttl=64 time=0.629 ms
64 bytes from 192.168.64.16: icmp_seq=2 ttl=64 time=0.692 ms
64 bytes from 192.168.64.16: icmp_seq=3 ttl=64 time=0.961 ms
64 bytes from 192.168.64.16: icmp_seq=4 ttl=64 time=0.693 ms
^C
--- 192.168.64.16 ping statistics ---
5 packets transmitted, 5 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 0.564/0.708/0.961/0.135 ms

**Comment by russmckendrick** [comment]
Hey, thanks for reaching out - it sounds like, for some reason, the host you are using is unable to take advantage of the https://nip.io/ service - so you could try using an alternative service such as:

- https://traefik.me/ (192.168.64.16.traefik.me)
- https://sslip.io (192.168.64.16.sslip.io)

Try using the `host` command from your terminal to see if they resolve:

<img width="1026" alt="SCR-20240707-kxlh-2" src="https://github.com/PacktPublishing/Learn-Ansible-Second-Edition/assets/121128/7db35d34-93ed-496a-b652-91e900753855">

If you don't have any luck with those, then you can try updating the inventory file so it reads something like the following:

```
testhost ansible_host=192.168.64.16 ansible_user=vmadmin ansible_private_key_file=./example_key
```

Russ

**Comment by wvelez6** [comment]
Thank you so much Russ. I can confirm that it was my firewall blocking nip.io. Also, I had to change permission of example_key to 600.

msg": "Failed to connect to the host via ssh: Warning: Permanently added '10.189.46.182.nip.io' (ED25519) to the list of known hosts.\r\n@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\r\n@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @\r\n@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\r\nPermissions 0664 for './example_key' are too open.\r\nIt is required that your private key files are NOT accessible by others.\r\nThis private key will be ignored.\r\nLoad key \"./example_key\": bad permissions\r\nvmadmin@10.189.46.182.nip.io: Permission denied (publickey).",
    "unreachable": true
    
B.T.W. with my Ubuntu laptop I get a 10.189.46.*** subnet as opposed to the 192.168.64.*** as I got with macOS.

Once again, thank you.

**Comment by russmckendrick** [comment]
Hi,

I'm glad you got there, and I hope you enjoy the rest of the book,

Russ
